export const SAMPLE_LOADING = "SAMPLE_LOADING";
export const SAMPLE_FORM_SUBMIT = "SAMPLE_FORM_SUBMIT";
export const SAMPLE_FORM_HTTP_REQUEST = "SAMPLE_FORM_HTTP_REQUEST";
export const SAMPLE_ADD = "SAMPLE_ADD";
export const SAMPLE_GET_PAGINATED_LIST = "SAMPLE_GET_PAGINATED_LIST";
export const SAMPLE_DELETE = "SAMPLE_DELETE";
export const SAMPLE_PAGNIATION_UPDATE = "SAMPLE_PAGNIATION_UPDATE";
export const SAMPLE_SUCCESS_TOAST = "SAMPLE_SUCCESS_TOAST";
export const SAMPLE_GET = "SAMPLE_GET";
export const SAMPLE_LAYOUT_STYLE = "SAMPLE_LAYOUT_STYLE";
export const SAMPLE_UPDATE = "SAMPLE_UPDATE";
export const SAMPLE_IS_INITIAL_TABLE_DATA_LOADED_UPDATE = "SAMPLE_IS_INITIAL_TABLE_DATA_LOADED_UPDATE";


